### ISSUE TITLE
a release would be great

### ISSUE THREAD

**Issue by hannesm** [stedolan/ocaml-afl-persistent#5]
Hi Stephen,

I wanted to install afl-persistent via opam right now, but on my FreeBSD system this fails, since the latest release (1.2) uses `#!/bin/bash` in `build.sh` -- a binary which does not exist on my system. Since #4 this issue is fixed in master, but not in the released opam package. It would be great to get a new release out. :)

Thanks!

**Comment by stedolan** [comment]
happening at ocaml/opam-repository#12978
