### ISSUE TITLE
Port to Dune

### ISSUE THREAD

**Issue by craigfe** [stedolan/ocaml-afl-persistent#6]
As discussed offline, it would be useful to port this package to use `dune` (e.g. in order to be able to pack it into a `duniverse`).

CC @avsm.

**Comment by stedolan** [comment]
Took a while to get around to this, but it's done now!

**Comment by tacerus** [comment]
Hi @stedolan, thank you for adding Dune support! Would it be possible to get a new release tag with this? It would help with distribution packaging.

Edit: seems it is already included in v1.4, sorry for the noise.
